[package]
authors = ["Simon Vandel Sillesen <simon.vandel@gmail.com>"]
name = "spwn"
version = "0.1.0"

[dependencies]
clap = "2.20.1"
curl = "0.4.4"
env_logger = "0.4.0"
futures = "0.1.10"
futures-cpupool = "0.1.2"
num_cpus = "1.2.1"
threadpool = "1.3.2"
tokio-core = "0.1.4"
tokio-curl = "0.1.9"
tokio-pool = "0.1.0"
tokio-timer = "0.1.0"
